export const languageChoices = [
  { code: 'zh-Hans', name: '简体中文', note: '试验版 · 未审核' },
  { code: 'id', name: 'Bahasa Indonesia', note: 'Uji coba · belum ditinjau' },
  { code: 'ja', name: '日本語', note: '試験版・未審査' },
  { code: 'ko', name: '한국어', note: '시험판 · 아직 검토되지 않음' },
  { code: 'hi', name: 'हिन्दी', note: 'प्रायोगिक · अभी समीक्षा नहीं हुई' },
] as const;

export type EntryLanguage = typeof languageChoices[number]['code'];
export type EntryCopy = {
  demo: string; title: [string, string]; intro: string; choose: string; chooseHint: string;
  trial: string; login: string; loginHint: string; wechat: string; unavailable: string;
  providerNotice: string; change: string; audio: string; permissions: string;
  permissionsCopy: string; storageCopy: string; settings: string; large: string;
  reduced: string; settingsHint: string; readError: string; saveError: string;
  respectTitle: string; respect: string; pace: string;
  notice: { open: string; close: string; title: string; paragraphs: [string, string] };
};

export const entryCopy: Record<EntryLanguage, EntryCopy> = {
  'zh-Hans': {
    demo: '流程演示', title: ['在新加坡，', '从听懂开始。'],
    intro: '从买一杯咖啡，到和老师聊聊孩子。让英语，一点点走进你的生活。',
    choose: '先选你熟悉的语言', chooseHint: '用于操作说明和帮助，随时可以更换。',
    trial: '语言试验版 · 文字与语音尚未经过母语审查',
    login: '选择登录方式', loginHint: '两个入口都可选。真实账号连接尚未接入。',
    wechat: '微信', unavailable: '尚未接入',
    providerNotice: '真实登录尚未接入。当前仍是流程演示，没有连接或创建账号。',
    change: '更换语言', audio: '听说明', permissions: '权限说明',
    permissionsCopy: '这里只展示流程，不申请麦克风或摄像头权限，也不会录音。未来练习可以只听；准备开口时，再由你决定是否开启麦克风。',
    storageCopy: '语言与显示设置只保存在这台设备的浏览器中，不与账号同步。清除浏览器数据后，需要重新选择。',
    settings: '显示设置', large: '大字', reduced: '减少动画',
    settingsHint: '按你舒服的方式阅读。设置只保存在本机。',
    readError: '无法读取本机设置；本次仍可选择并继续，刷新后可能需要重新选择。',
    saveError: '无法保存本机设置；本次选择仍有效，刷新后可能需要重新选择。',
    respectTitle: '尊重每一种口音',
    respect: '英语有多种口音和方言，都值得尊重。这里帮助你熟悉新加坡英语及本地表达；你可以保留自己的口音。听不懂时，可以放慢、再听一次，也可以请对方换个说法。',
    pace: '听优先，按自己的节奏。',
    notice: { open: '查看演示说明', close: '收起演示说明', title: '演示说明', paragraphs: ['这是本地流程演示。真实登录、语音和视频尚未接入，暂时不能开始正式练习。', '你可以先了解练习方式。这里不会录音，也不会连接真实账号。'] },
  },
  id: {
    demo: 'Demo alur', title: ['Di Singapura,', 'mulai dengan mendengar.'],
    intro: 'Dari memesan kopi hingga berbicara dengan guru anak Anda. Mulai gunakan bahasa Inggris dalam keseharian, sedikit demi sedikit.',
    choose: 'Pilih bahasa yang Anda pahami', chooseHint: 'Untuk petunjuk dan bantuan. Anda dapat menggantinya kapan saja.',
    trial: 'Versi uji coba · teks dan suara belum ditinjau oleh penutur asli',
    login: 'Pilih cara masuk', loginHint: 'Kedua pilihan tersedia untuk semua pengguna. Koneksi akun belum terhubung.',
    wechat: 'WeChat', unavailable: 'Belum terhubung',
    providerNotice: 'Layanan masuk belum terhubung. Ini masih demo alur; tidak ada akun yang dihubungkan atau dibuat.',
    change: 'Ganti bahasa', audio: 'Dengarkan petunjuk', permissions: 'Izin dan privasi',
    permissionsCopy: 'Demo ini tidak meminta akses mikrofon atau kamera dan tidak merekam. Dalam latihan mendatang, Anda boleh hanya mendengarkan. Anda yang memutuskan kapan ingin mengaktifkan mikrofon.',
    storageCopy: 'Bahasa dan pengaturan tampilan disimpan hanya di peramban perangkat ini, tanpa sinkronisasi akun. Setelah data peramban dihapus, pilih kembali pengaturan Anda.',
    settings: 'Pengaturan tampilan', large: 'Teks besar', reduced: 'Kurangi animasi',
    settingsHint: 'Pilih tampilan yang nyaman. Pengaturan disimpan di perangkat ini saja.',
    readError: 'Pengaturan perangkat tidak dapat dibaca. Pilihan tetap berlaku saat ini; setelah memuat ulang, Anda mungkin perlu memilih lagi.',
    saveError: 'Pengaturan perangkat tidak dapat disimpan. Pilihan tetap berlaku saat ini; setelah memuat ulang, Anda mungkin perlu memilih lagi.',
    respectTitle: 'Setiap aksen patut dihargai',
    respect: 'Bahasa Inggris memiliki beragam aksen dan dialek, dan semuanya patut dihargai. Di sini Anda dapat mengenal bahasa Inggris Singapura dan ungkapan setempat; Anda boleh mempertahankan aksen Anda sendiri. Jika belum memahami, Anda dapat memperlambat, mendengarkan lagi, atau meminta lawan bicara menjelaskan dengan cara lain.',
    pace: 'Dengarkan dahulu, sesuai ritme Anda.',
    notice: { open: 'Lihat penjelasan demo', close: 'Tutup penjelasan demo', title: 'Penjelasan demo', paragraphs: ['Ini adalah demo alur lokal. Layanan masuk, suara, dan video belum terhubung; latihan sesungguhnya belum tersedia.', 'Anda dapat mengenal alur latihan terlebih dahulu. Demo ini tidak merekam dan tidak menghubungkan akun sungguhan.'] },
  },
  ja: {
    demo: '操作デモ', title: ['シンガポールで、', '聞いてわかることから。'],
    intro: 'コーヒーを頼むときも、子どもの先生と話すときも。少しずつ、暮らしの中で英語を使ってみましょう。',
    choose: '使い慣れた言語を選ぶ', chooseHint: '操作説明やサポートに使います。いつでも変更できます。',
    trial: '言語の試験版・文章と音声は母語話者による確認前です',
    login: 'ログイン方法を選ぶ', loginHint: 'どちらの方法も選べます。実際のアカウント連携は未接続です。',
    wechat: 'WeChat', unavailable: '未接続',
    providerNotice: '実際のログイン機能は未接続です。現在は操作デモで、アカウントの連携や作成は行っていません。',
    change: '言語を変更', audio: '説明を聞く', permissions: '権限とプライバシー',
    permissionsCopy: 'このデモはマイクやカメラの権限を求めず、録音もしません。今後の練習でも、聞くだけで利用できます。話したくなったときに、自分でマイクの使用を選べます。',
    storageCopy: '言語と表示設定は、この端末のブラウザーだけに保存されます。アカウントとの同期はありません。ブラウザーのデータを消去すると、選び直す必要があります。',
    settings: '表示設定', large: '大きな文字', reduced: '動きを減らす',
    settingsHint: '読みやすい表示を選べます。設定はこの端末だけに保存されます。',
    readError: '端末の設定を読み取れません。今回の選択は使えますが、再読み込み後に選び直す必要がある場合があります。',
    saveError: '端末に設定を保存できません。今回の選択は使えますが、再読み込み後に選び直す必要がある場合があります。',
    respectTitle: 'どのアクセントも大切に',
    respect: '英語にはさまざまなアクセントや方言があり、すべて尊重されるものです。ここではシンガポール英語や地域の表現に慣れるお手伝いをします。自分のアクセントを保ったままでかまいません。聞き取れないときは、速度を落としてもう一度聞いたり、別の言い方をお願いしたりできます。',
    pace: 'まずは聞くことから。自分のペースで。',
    notice: { open: 'デモの説明を見る', close: 'デモの説明を閉じる', title: 'デモの説明', paragraphs: ['これはローカルの操作デモです。実際のログイン、音声、動画は未接続で、正式な練習はまだ利用できません。', '練習の流れを先に確認できます。録音や実際のアカウント連携は行いません。'] },
  },
  ko: {
    demo: '흐름 데모', title: ['싱가포르에서,', '듣기부터 시작하세요.'],
    intro: '커피 주문부터 아이의 선생님과 대화하기까지, 생활 속 영어를 조금씩 익혀 보세요.',
    choose: '익숙한 언어를 선택하세요', chooseHint: '안내와 도움에 사용하며 언제든 바꿀 수 있습니다.',
    trial: '시험판 언어 · 글과 음성은 아직 원어민 검토 전입니다',
    login: '로그인 방법 선택', loginHint: '두 방법 모두 선택할 수 있습니다. 실제 계정 연결은 아직 준비 중입니다.',
    wechat: 'WeChat', unavailable: '아직 연결되지 않음',
    providerNotice: '실제 로그인은 아직 연결되지 않았습니다. 현재는 흐름 데모이며 계정을 연결하거나 만들지 않습니다.',
    change: '언어 변경', audio: '안내 듣기', permissions: '권한 및 개인정보',
    permissionsCopy: '이 데모는 마이크나 카메라 권한을 요청하지 않고 녹음하지 않습니다. 앞으로의 연습에서도 듣기만 할 수 있으며, 말할 준비가 되었을 때 직접 마이크 사용을 선택합니다.',
    storageCopy: '언어와 화면 설정은 이 기기의 브라우저에만 저장되며 계정과 동기화되지 않습니다. 브라우저 데이터를 지우면 다시 선택해야 합니다.',
    settings: '화면 설정', large: '큰 글자', reduced: '동작 줄이기',
    settingsHint: '편하게 읽을 수 있는 화면을 선택하세요. 설정은 이 기기에만 저장됩니다.',
    readError: '기기 설정을 읽을 수 없습니다. 이번에는 계속할 수 있지만 새로고침 후 다시 선택해야 할 수 있습니다.',
    saveError: '기기 설정을 저장할 수 없습니다. 이번 선택은 유지되지만 새로고침 후 다시 선택해야 할 수 있습니다.',
    respectTitle: '모든 억양을 존중합니다',
    respect: '영어에는 다양한 억양과 방언이 있으며 모두 존중받아야 합니다. 여기서는 싱가포르 영어와 현지 표현에 익숙해질 수 있고 자신의 억양을 그대로 유지해도 됩니다. 잘 들리지 않으면 천천히 말해 달라고 하거나 다시 듣고 다른 표현을 요청할 수 있습니다.',
    pace: '먼저 듣고, 내 속도로.',
    notice: { open: '데모 설명 보기', close: '데모 설명 닫기', title: '데모 설명', paragraphs: ['이것은 로컬 흐름 데모입니다. 실제 로그인, 음성, 영상은 아직 연결되지 않아 정식 연습은 할 수 없습니다.', '먼저 연습 흐름을 살펴볼 수 있습니다. 녹음하거나 실제 계정을 연결하지 않습니다.'] },
  },
  hi: {
    demo: 'फ़्लो डेमो', title: ['सिंगापुर में,', 'सुनने से शुरुआत करें।'],
    intro: 'कॉफ़ी मँगाने से लेकर अपने बच्चे के शिक्षक से बात करने तक, रोज़मर्रा में धीरे-धीरे अंग्रेज़ी अपनाएँ।',
    choose: 'अपनी परिचित भाषा चुनें', chooseHint: 'निर्देश और मदद के लिए। इसे कभी भी बदला जा सकता है।',
    trial: 'प्रायोगिक भाषा · टेक्स्ट और आवाज़ की अभी मातृभाषी समीक्षा नहीं हुई',
    login: 'साइन इन करने का तरीका चुनें', loginHint: 'दोनों विकल्प सभी के लिए हैं। असली अकाउंट कनेक्शन अभी उपलब्ध नहीं हैं।',
    wechat: 'WeChat', unavailable: 'अभी कनेक्ट नहीं है',
    providerNotice: 'असली साइन-इन अभी कनेक्ट नहीं है। यह फ़्लो डेमो है; कोई अकाउंट जोड़ा या बनाया नहीं जाता।',
    change: 'भाषा बदलें', audio: 'निर्देश सुनें', permissions: 'अनुमतियाँ और गोपनीयता',
    permissionsCopy: 'यह डेमो माइक्रोफ़ोन या कैमरे की अनुमति नहीं माँगता और रिकॉर्ड नहीं करता। आगे के अभ्यास में आप केवल सुन सकते हैं। बोलने के लिए तैयार होने पर माइक्रोफ़ोन चालू करना आपके हाथ में है।',
    storageCopy: 'भाषा और डिस्प्ले सेटिंग केवल इस डिवाइस के ब्राउज़र में रहती हैं और अकाउंट से सिंक नहीं होतीं। ब्राउज़र डेटा मिटाने पर फिर चुनना होगा।',
    settings: 'डिस्प्ले सेटिंग', large: 'बड़ा टेक्स्ट', reduced: 'एनिमेशन कम करें',
    settingsHint: 'जिस तरह पढ़ना सहज हो, वह चुनें। सेटिंग केवल इस डिवाइस में रहती हैं।',
    readError: 'डिवाइस की सेटिंग पढ़ी नहीं जा सकीं। अभी जारी रख सकते हैं; रीफ़्रेश के बाद फिर चुनना पड़ सकता है।',
    saveError: 'डिवाइस की सेटिंग सहेजी नहीं जा सकीं। अभी का चुनाव काम करेगा; रीफ़्रेश के बाद फिर चुनना पड़ सकता है।',
    respectTitle: 'हर उच्चारण सम्मान के योग्य है',
    respect: 'अंग्रेज़ी के कई उच्चारण और बोलियाँ हैं और सभी सम्मान के योग्य हैं। यहाँ आप सिंगापुर की अंग्रेज़ी और स्थानीय अभिव्यक्तियों से परिचित होंगे; अपना उच्चारण बनाए रख सकते हैं। समझ न आए तो धीमा करने, दोबारा सुनने या दूसरे तरीके से कहने को कहें।',
    pace: 'पहले सुनें, अपनी गति से।',
    notice: { open: 'डेमो की जानकारी देखें', close: 'डेमो की जानकारी बंद करें', title: 'डेमो की जानकारी', paragraphs: ['यह स्थानीय फ़्लो डेमो है। असली साइन-इन, आवाज़ और वीडियो अभी जुड़े नहीं हैं, इसलिए पूरा अभ्यास उपलब्ध नहीं है।', 'आप पहले अभ्यास का तरीका देख सकते हैं। यह डेमो रिकॉर्ड या असली अकाउंट कनेक्ट नहीं करता।'] },
  },
};
