import type { EntryLanguage } from './entry-copy';
const zh = {
  entry: '预览听与练', title: '先听懂，再试着说', roles: '两位演示角色', partner: '对方 · 演示角色 A', visitor: '来访者 · 演示角色 B', yours: '你的位置',
  demo: '没有真实声音或视频', review: '尚未经本地与教学审查', generic: '以下是固定通用示例；你的目的保留原文，尚未翻译成英语课程。文字可作辅助，不需要朗读或作答。',
  version: '版本', goal: '这次想办的事', unknown: '口语尚未观察', current: '当前一句', practice: '我来练', start: '开始听（演示）',
  status: '练习状态', settings: '播放设置', gesture: '点一下，让对方先开始', listening: '先听示范就好', opening: '对方先开场', awaiting: '轮到你，按自己的节奏',
  hint1: '先听一个提示', hint2: '可以选择你的意思', thinking: '慢慢想，不会催你', speaking: '正在说话（模拟）', replying: '对方准备回应（模拟）', resuming: '对方带你接着练',
  paused: '已暂停', disconnected: '连接已暂停（模拟）', denied: '麦克风不可用', inaudible: '声音已暂停（模拟）', background: '已暂停，回来后可以继续', ended: '本次预览已结束',
  previous: '前一句', sentence: '单句循环', chapter: '章节循环', all: '整段循环', ab: 'A-B 片段循环', from: '片段起点', to: '片段终点',
  slow: '慢一点', natural: '自然速度', speedHint: '这里只保存速度选择，尚未真正变速。', pause: '停一下', think: '我想一想', resume: '继续', manual: '手动说话（尚未接入）',
  finished: '我说完了', listen: '只听示范', help: '给个提示', other: '需要其他帮助', choices: '意思选择', ask: '我想问一件事', again: '我想再听一遍',
  patience: '多等一会', six: '默认等待', ten: '多等一会', fifteen: '再多等一会', proactive: '主动提示', retry: '重试连接（演示）', exit: '结束本次预览',
  controls: '演示轮次控制', controlHint: '这些按钮只推进演示事件，不播放或录制声音，也不测量真实等待。', endPlayback: '模拟本句播放结束', wait: '模拟经过 6 秒',
  speech: '模拟开始说话', deny: '模拟麦克风不可用', disconnect: '模拟断开连接', saveError: '练习预览暂时无法保存，本次仍可继续', readError: '旧练习记录保持不变，本次仅临时预览。', active: '正在示范（模拟）', resting: '在听',
};
type Copy = { [K in keyof typeof zh]: string };
const en: Copy = {
  entry:'Preview listening and practice', title:'Listen first, then try speaking', roles:'Two demonstration characters', partner:'Partner · demo character A', visitor:'Visitor · demo character B', yours:'Your place',
  demo:'No real audio or video', review:'Not yet reviewed locally or by a teacher', generic:'These are fixed, general examples. Your original goal is kept as entered; it has not been translated into an English lesson. Text is optional support. No reading aloud or answer is required.',
  version:'Version', goal:'What you want to accomplish', unknown:'Speaking has not been observed', current:'Current line', practice:'Let me practise', start:'Start listening (demo)',
  status:'Practice status', settings:'Playback settings', gesture:'Tap to let your partner begin', listening:'You can just listen', opening:'Your partner starts', awaiting:'Your turn, at your own pace',
  hint1:'Listen to one hint', hint2:'Choose what you mean', thinking:'Take your time; no hurry', speaking:'Speaking (simulated)', replying:'Your partner is preparing a reply (simulated)', resuming:'Your partner guides you back in',
  paused:'Paused', disconnected:'Connection paused (simulated)', denied:'Microphone unavailable', inaudible:'Sound paused (simulated)', background:'Paused; continue when you return', ended:'Preview ended',
  previous:'Previous line', sentence:'Repeat this line', chapter:'Repeat chapter', all:'Repeat all', ab:'Repeat A-B section', from:'Section start', to:'Section end',
  slow:'Slower', natural:'Natural speed', speedHint:'This saves a speed preference; playback speed is not changed yet.', pause:'Pause for a moment', think:'Let me think', resume:'Continue', manual:'Speak manually (not connected)',
  finished:'I have finished', listen:'Just listen', help:'Give me a hint', other:'I need other help', choices:'Meaning choices', ask:'I want to ask something', again:'I want to hear it again',
  patience:'Wait a little longer', six:'Default wait', ten:'A little longer', fifteen:'Even longer', proactive:'Proactive hints', retry:'Retry connection (demo)', exit:'End this preview',
  controls:'Demo turn controls', controlHint:'These buttons advance simulated events only. They do not play or record audio, or measure real waiting times.', endPlayback:'Simulate this line ending', wait:'Simulate 6 seconds passing',
  speech:'Simulate starting to speak', deny:'Simulate unavailable microphone', disconnect:'Simulate disconnection', saveError:'This preview cannot be saved right now; you can continue this time', readError:'Your old practice record is unchanged. This preview is temporary.', active:'Demonstrating (simulated)', resting:'Listening',
};
const id: Copy = {
  entry:'Pratinjau mendengar dan berlatih', title:'Pahami dahulu, lalu coba berbicara', roles:'Dua tokoh demonstrasi', partner:'Lawan bicara · tokoh demo A', visitor:'Pengunjung · tokoh demo B', yours:'Posisi Anda',
  demo:'Tidak ada suara atau video nyata', review:'Belum ditinjau oleh penutur lokal dan pengajar', generic:'Ini contoh umum yang tetap. Tujuan Anda disimpan dalam bahasa aslinya, belum diterjemahkan menjadi pelajaran Inggris. Teks hanya bantuan pilihan; tidak perlu membaca keras atau menjawab.',
  version:'Versi', goal:'Hal yang ingin Anda lakukan', unknown:'Kemampuan berbicara belum diamati', current:'Kalimat saat ini', practice:'Saya mau berlatih', start:'Mulai mendengar (demo)',
  status:'Status latihan', settings:'Pengaturan pemutaran', gesture:'Ketuk agar lawan bicara memulai', listening:'Boleh mendengarkan saja', opening:'Lawan bicara memulai', awaiting:'Giliran Anda, santai saja',
  hint1:'Dengarkan satu petunjuk', hint2:'Pilih maksud Anda', thinking:'Pikirkan pelan-pelan, tidak terburu-buru', speaking:'Sedang berbicara (simulasi)', replying:'Lawan bicara menyiapkan jawaban (simulasi)', resuming:'Lawan bicara membantu Anda melanjutkan',
  paused:'Dijeda', disconnected:'Koneksi dijeda (simulasi)', denied:'Mikrofon tidak tersedia', inaudible:'Suara dijeda (simulasi)', background:'Dijeda; lanjutkan saat kembali', ended:'Pratinjau berakhir',
  previous:'Kalimat sebelumnya', sentence:'Ulangi kalimat ini', chapter:'Ulangi bagian', all:'Ulangi semuanya', ab:'Ulangi potongan A-B', from:'Awal potongan', to:'Akhir potongan',
  slow:'Lebih pelan', natural:'Kecepatan alami', speedHint:'Ini hanya menyimpan pilihan kecepatan, belum mengubah suara.', pause:'Berhenti sebentar', think:'Saya mau berpikir', resume:'Lanjutkan', manual:'Bicara manual (belum terhubung)',
  finished:'Saya sudah selesai', listen:'Dengarkan saja', help:'Beri petunjuk', other:'Saya butuh bantuan lain', choices:'Pilihan maksud', ask:'Saya ingin bertanya', again:'Saya ingin mendengar lagi',
  patience:'Tunggu lebih lama', six:'Waktu tunggu biasa', ten:'Sedikit lebih lama', fifteen:'Lebih lama lagi', proactive:'Petunjuk otomatis', retry:'Coba koneksi lagi (demo)', exit:'Akhiri pratinjau ini',
  controls:'Kontrol giliran demo', controlHint:'Tombol ini hanya menggerakkan simulasi, tanpa memutar atau merekam suara dan tanpa mengukur waktu nyata.', endPlayback:'Simulasikan akhir kalimat', wait:'Simulasikan berlalu 6 detik',
  speech:'Simulasikan mulai berbicara', deny:'Simulasikan mikrofon tidak tersedia', disconnect:'Simulasikan koneksi terputus', saveError:'Pratinjau belum bisa disimpan; Anda masih bisa melanjutkan', readError:'Catatan latihan lama tetap utuh. Pratinjau ini sementara.', active:'Memberi contoh (simulasi)', resting:'Mendengarkan',
};
const ja: Copy = {
  entry:'聞く・話す流れをプレビュー', title:'まず聞いてから、話してみる', roles:'2人のデモキャラクター', partner:'相手役 · デモ A', visitor:'訪問者役 · デモ B', yours:'あなたの位置',
  demo:'実際の音声や動画はありません', review:'現地の話者・指導者による確認はまだです', generic:'固定の一般的な例です。目的は入力した言語のまま保存し、英語教材への翻訳はまだ行っていません。文字は任意の補助です。音読や回答は不要です。',
  version:'バージョン', goal:'今回したいこと', unknown:'話す力はまだ観察していません', current:'今の一文', practice:'自分で練習する', start:'聞き始める（デモ）',
  status:'練習の状態', settings:'再生設定', gesture:'タップすると相手から始めます', listening:'聞くだけでも大丈夫です', opening:'相手から話し始めます', awaiting:'あなたのペースでどうぞ',
  hint1:'ヒントを一つ聞きましょう', hint2:'伝えたい意味を選べます', thinking:'ゆっくり考えて大丈夫です', speaking:'話している状態（シミュレーション）', replying:'相手が返事を準備中（シミュレーション）', resuming:'相手が続きへ案内します',
  paused:'一時停止中', disconnected:'接続を一時停止（シミュレーション）', denied:'マイクを利用できません', inaudible:'音声を一時停止（シミュレーション）', background:'一時停止中。戻ったら続けられます', ended:'プレビューを終了しました',
  previous:'前の一文', sentence:'一文を繰り返す', chapter:'章を繰り返す', all:'全体を繰り返す', ab:'A-B 区間を繰り返す', from:'区間の始点', to:'区間の終点',
  slow:'もっとゆっくり', natural:'自然な速さ', speedHint:'速さの設定だけを保存します。実際の音声速度はまだ変わりません。', pause:'いったん止める', think:'少し考えたい', resume:'続ける', manual:'手動で話す（未接続）',
  finished:'話し終わりました', listen:'お手本を聞くだけ', help:'ヒントをください', other:'別の助けが必要です', choices:'意味の選択肢', ask:'質問したいです', again:'もう一度聞きたいです',
  patience:'もう少し待つ', six:'通常の待ち時間', ten:'少し長めに待つ', fifteen:'さらに長めに待つ', proactive:'自動ヒント', retry:'接続を再試行（デモ）', exit:'今回のプレビューを終了',
  controls:'デモのターン操作', controlHint:'このボタンは模擬イベントだけを進めます。音声の再生・録音や実際の待ち時間の測定はしません。', endPlayback:'一文の再生終了を模擬', wait:'6秒の経過を模擬',
  speech:'発話開始を模擬', deny:'マイクが使えない状態を模擬', disconnect:'切断を模擬', saveError:'今は練習を保存できませんが、このまま続けられます', readError:'以前の練習記録はそのままです。今回は一時的なプレビューです。', active:'お手本の動作（シミュレーション）', resting:'聞いています',
};
const ko: Copy = {...en,
  entry:'듣기와 말하기 미리보기',title:'먼저 듣고, 말해 보세요',roles:'두 명의 데모 캐릭터',partner:'상대역 · 데모 A',visitor:'방문자역 · 데모 B',yours:'내 자리',demo:'실제 음성이나 영상 없음',review:'현지 및 교육 검토 전',generic:'고정된 일반 예시입니다. 입력한 목적은 원문 그대로 유지됩니다. 글은 선택 도움이며 소리 내 읽거나 답할 필요가 없습니다.',version:'버전',goal:'이루고 싶은 일',unknown:'말하기는 아직 관찰되지 않았습니다',current:'현재 문장',practice:'직접 연습하기',start:'듣기 시작(데모)',status:'연습 상태',settings:'재생 설정',gesture:'눌러서 상대가 먼저 말하게 하기',listening:'듣기만 해도 됩니다',opening:'상대가 먼저 시작합니다',awaiting:'내 차례, 내 속도로',hint1:'힌트 하나 듣기',hint2:'뜻 선택하기',thinking:'천천히 생각해도 됩니다',speaking:'말하는 중(시뮬레이션)',replying:'상대가 답변 준비 중(시뮬레이션)',resuming:'상대가 다시 대화로 안내합니다',paused:'일시 중지됨',disconnected:'연결 일시 중지(시뮬레이션)',denied:'마이크를 사용할 수 없음',inaudible:'소리 일시 중지(시뮬레이션)',background:'일시 중지됨. 돌아오면 계속하세요',ended:'미리보기 종료',previous:'이전 문장',sentence:'이 문장 반복',chapter:'장 반복',all:'전체 반복',ab:'A-B 구간 반복',from:'구간 시작',to:'구간 끝',slow:'더 천천히',natural:'자연스러운 속도',speedHint:'속도 선호도만 저장하며 실제 재생 속도는 아직 바뀌지 않습니다.',pause:'잠시 멈추기',think:'생각할게요',resume:'계속',manual:'수동으로 말하기(미연결)',finished:'말을 마쳤어요',listen:'듣기만 하기',help:'힌트 주세요',other:'다른 도움이 필요해요',choices:'뜻 선택',ask:'질문하고 싶어요',again:'다시 듣고 싶어요',patience:'조금 더 기다리기',six:'기본 대기',ten:'조금 더 길게',fifteen:'더 길게',proactive:'자동 힌트',retry:'연결 다시 시도(데모)',exit:'미리보기 끝내기',controls:'데모 차례 제어',controlHint:'이 버튼은 시뮬레이션만 진행하며 음성을 재생·녹음하거나 실제 시간을 측정하지 않습니다.',endPlayback:'문장 재생 종료 시뮬레이션',wait:'6초 경과 시뮬레이션',speech:'말하기 시작 시뮬레이션',deny:'마이크 사용 불가 시뮬레이션',disconnect:'연결 끊김 시뮬레이션',saveError:'미리보기를 저장할 수 없지만 계속할 수 있습니다',readError:'이전 기록은 그대로이며 이번 미리보기는 임시입니다.',active:'시범 중(시뮬레이션)',resting:'듣는 중'};
const hi: Copy = {...en,
  entry:'सुनने और बोलने का पूर्वावलोकन',title:'पहले सुनें, फिर बोलने की कोशिश करें',roles:'दो डेमो पात्र',partner:'सामने वाला · डेमो A',visitor:'आगंतुक · डेमो B',yours:'आपकी जगह',demo:'असली आवाज़ या वीडियो नहीं',review:'स्थानीय और शिक्षकीय समीक्षा अभी नहीं हुई',generic:'ये तय सामान्य उदाहरण हैं। आपका लक्ष्य उसी भाषा में सुरक्षित है जिसमें आपने लिखा था। टेक्स्ट वैकल्पिक मदद है; पढ़कर बोलना या उत्तर देना ज़रूरी नहीं।',version:'संस्करण',goal:'आप क्या हासिल करना चाहते हैं',unknown:'बोलना अभी देखा नहीं गया',current:'मौजूदा वाक्य',practice:'मैं अभ्यास करूँगा/करूँगी',start:'सुनना शुरू करें (डेमो)',status:'अभ्यास की स्थिति',settings:'प्लेबैक सेटिंग',gesture:'सामने वाले को शुरू कराने के लिए टैप करें',listening:'आप केवल सुन सकते हैं',opening:'सामने वाला पहले शुरू करता है',awaiting:'आपकी बारी, अपनी गति से',hint1:'एक संकेत सुनें',hint2:'अपना अर्थ चुनें',thinking:'आराम से सोचें',speaking:'बोल रहे हैं (डेमो)',replying:'सामने वाला उत्तर तैयार कर रहा है (डेमो)',resuming:'सामने वाला बातचीत में वापस लाता है',paused:'रुका हुआ',disconnected:'कनेक्शन रुका (डेमो)',denied:'माइक्रोफ़ोन उपलब्ध नहीं',inaudible:'आवाज़ रुकी (डेमो)',background:'रुका हुआ; लौटकर जारी रखें',ended:'पूर्वावलोकन समाप्त',previous:'पिछला वाक्य',sentence:'यह वाक्य दोहराएँ',chapter:'खंड दोहराएँ',all:'सब दोहराएँ',ab:'A-B हिस्सा दोहराएँ',from:'हिस्से की शुरुआत',to:'हिस्से का अंत',slow:'और धीमा',natural:'स्वाभाविक गति',speedHint:'यह केवल गति की पसंद सहेजता है; असली प्लेबैक गति अभी नहीं बदलती।',pause:'थोड़ा रुकें',think:'मुझे सोचने दें',resume:'जारी रखें',manual:'खुद बोलें (अभी जुड़ा नहीं)',finished:'मैंने बोलना पूरा किया',listen:'केवल सुनें',help:'एक संकेत दें',other:'मुझे दूसरी मदद चाहिए',choices:'अर्थ के विकल्प',ask:'मैं कुछ पूछना चाहता/चाहती हूँ',again:'मैं फिर सुनना चाहता/चाहती हूँ',patience:'थोड़ा और प्रतीक्षा',six:'सामान्य प्रतीक्षा',ten:'थोड़ी लंबी',fifteen:'और लंबी',proactive:'अपने-आप संकेत',retry:'कनेक्शन फिर आज़माएँ (डेमो)',exit:'पूर्वावलोकन समाप्त करें',controls:'डेमो टर्न नियंत्रण',controlHint:'ये बटन केवल डेमो घटनाएँ चलाते हैं; आवाज़ नहीं चलाते या रिकॉर्ड करते और असली समय नहीं मापते।',endPlayback:'वाक्य खत्म होने का डेमो',wait:'6 सेकंड बीतने का डेमो',speech:'बोलना शुरू होने का डेमो',deny:'माइक्रोफ़ोन न मिलने का डेमो',disconnect:'कनेक्शन टूटने का डेमो',saveError:'अभी पूर्वावलोकन सहेजा नहीं जा सकता; जारी रख सकते हैं',readError:'पुराना अभ्यास रिकॉर्ड सुरक्षित है। यह पूर्वावलोकन अस्थायी है।',active:'उदाहरण चल रहा है (डेमो)',resting:'सुन रहे हैं'};
export function practiceCopy(language: EntryLanguage): Copy { return language === 'zh-Hans' ? zh : language === 'id' ? id : language === 'ja' ? ja : language === 'ko' ? ko : hi; }
