import type { EntryLanguage } from './entry-copy';
type Translation = readonly [string, string, string, string];
const index: Record<EntryLanguage, number> = { 'zh-Hans': 0, id: 1, ja: 2, en: 3 };
const labels = {
  entry: ['选择要练的事', 'Pilih hal yang ingin dilatih', '練習したいことを選ぶ', 'Choose what to practise'],
  title: ['你想练什么事？', 'Apa yang ingin Anda latih?', 'どんなことを練習したいですか？', 'What would you like to practise?'],
  intro: ['从一件近期想办的事开始。可以选一个起点，也可以用熟悉的语言说自己的目的。', 'Mulai dari satu hal yang ingin Anda lakukan. Pilih titik awal atau ceritakan tujuan dalam bahasa yang nyaman.', '近いうちにしたいことから始めましょう。例を選んでも、使い慣れた言葉で目的を伝えても構いません。', 'Start with something you want to do soon. Choose an example or describe your goal in a familiar language.'],
  demo: ['离线整理演示，不是实际生成', 'Demo penyusunan offline, bukan pembuatan sebenarnya', 'オフラインで整理するデモです。実際の生成ではありません', 'Offline planning demo, not actual generation'],
  demoHint: ['这里用通用沟通模板演示步骤，不表示已理解任意需求。辅助语言文案尚未经母语审查。', 'Langkah memakai templat komunikasi umum, bukan pemahaman semua kebutuhan. Teks belum ditinjau penutur asli.', '一般的な会話テンプレートで流れを示します。あらゆる要望を理解したわけではありません。文面は母語話者による未確認です。', 'These steps use generic communication templates, without claiming to understand every request. Translations have not had native-speaker review.'],
  starts: ['场景起点', 'Titik awal situasi', '場面の出発点', 'Scenario starting points'],
  school: ['家校沟通', 'Komunikasi dengan sekolah', '学校とのやりとり', 'School conversations'],
  work: ['工作沟通', 'Komunikasi kerja', '仕事でのやりとり', 'Work conversations'],
  daily: ['生活服务', 'Layanan sehari-hari', '暮らしのサービス', 'Everyday services'],
  custom: ['都不是，我想练……', 'Bukan ini, saya ingin berlatih…', 'どれでもない、練習したいことは…', 'None of these, I want to practise…'],
  description: ['想练的事', 'Hal yang ingin dilatih', '練習したいこと', 'What you want to practise'],
  describeHint: ['例如：陪邻居向物业询问维修时间。只说你愿意留下的内容。', 'Contoh: menemani tetangga menanyakan waktu perbaikan. Tulis hanya yang ingin Anda simpan.', '例：近所の人と修理の時間を窓口で聞きたい。残したい内容だけを書いてください。', 'For example: help a neighbour ask about repair times. Only include what you want to keep.'],
  privacy: ['无需真实姓名、学校、雇主或病历', 'Tidak perlu nama asli, sekolah, pemberi kerja, atau rekam medis', '実名、学校名、勤務先、診療記録は不要です', 'No real names, schools, employers, or medical records are needed'],
  voice: ['用语音描述（尚未接入）', 'Ceritakan dengan suara (belum terhubung)', '声で説明する（未接続）', 'Describe by voice (not connected)'],
  submit: ['整理成确认卡', 'Susun kartu konfirmasi', '確認カードにまとめる', 'Make a confirmation card'],
  clarifyTitle: ['你希望办成什么？', 'Apa yang ingin Anda capai?', '何をできるようになりたいですか？', 'What do you want to accomplish?'],
  clarifyHint: ['先补这一个目的，其他不知道的内容可以留空。', 'Cukup tambahkan tujuan ini. Hal lain yang belum diketahui boleh kosong.', 'まず目的だけを教えてください。ほかの不明なことは空欄で構いません。', 'Add just this goal. Other unknown details can stay blank.'],
  continue: ['继续确认', 'Lanjutkan konfirmasi', '確認へ進む', 'Continue to confirmation'],
  card: ['确认场景', 'Konfirmasi situasi', '場面を確認', 'Confirm the situation'],
  who: ['和谁', 'Dengan siapa', '誰と', 'Who with'], where: ['在哪里', 'Di mana', 'どこで', 'Where'],
  goal: ['希望办成什么', 'Hasil yang diinginkan', '実現したいこと', 'What you want to accomplish'],
  worry: ['最担心哪一步', 'Bagian yang dikhawatirkan', '一番心配なところ', 'What worries you most'],
  unknown: ['待确认', 'Belum dikonfirmasi', '未確認', 'To be confirmed'],
  userProvided: ['用户提供', 'Diberikan pengguna', '利用者からの情報', 'User-provided'],
  seed: ['来自规格中的练习种子，人物与情境为演示', 'Contoh dari spesifikasi; tokoh dan situasi untuk demo', '仕様書の練習例です。人物と場面はデモ用です', 'Practice seed from the specification; people and setting are illustrative'],
  editWho: ['修改谁', 'Ubah lawan bicara', '相手を変える', 'Change who'],
  editWhere: ['修改地点', 'Ubah tempat', '場所を変える', 'Change place'],
  editGoal: ['修改目的', 'Ubah tujuan', '目的を変える', 'Change goal'],
  editWorry: ['修改担心', 'Ubah kekhawatiran', '心配なことを変える', 'Change concern'],
  save: ['保存修改', 'Simpan perubahan', '変更を保存', 'Save changes'],
  discard: ['返回确认', 'Kembali ke konfirmasi', '確認に戻る', 'Back to confirmation'],
  candidates: ['可选的练习方向', 'Pilihan fokus latihan', '選べる練習の方向', 'Practice focus options'],
  candidateHint: ['保留你的目的，一次只练一个沟通重点。', 'Tujuan Anda tetap sama; latih satu fokus komunikasi sekaligus.', '目的はそのままに、一度に一つのやりとりを練習します。', 'Keep your goal and practise one communication focus at a time.'],
  confirm: ['确认并预览准备', 'Konfirmasi dan pratinjau persiapan', '確認して準備をプレビュー', 'Confirm and preview preparation'],
  preparing: ['正在准备（流程演示）', 'Sedang menyiapkan (demo alur)', '準備中（流れのデモ）', 'Preparing (flow demo)'],
  partial: ['部分准备未就绪（演示）', 'Sebagian persiapan belum siap (demo)', '準備の一部が未完了です（デモ）', 'Some preparation is not ready (demo)'],
  ready: ['场景草稿已备好（演示）', 'Draf situasi sudah siap (demo)', '場面の下書きができました（デモ）', 'Scenario draft is ready (demo)'],
  cancelled: ['已取消准备', 'Persiapan dibatalkan', '準備をキャンセルしました', 'Preparation cancelled'],
  version: ['版本 {n}', 'Versi {n}', 'バージョン {n}', 'Version {n}'],
  view: ['查看版本 {n}', 'Lihat versi {n}', 'バージョン {n} を見る', 'View version {n}'],
  history: ['已确认的版本', 'Versi yang dikonfirmasi', '確認済みのバージョン', 'Confirmed versions'],
  unchanged: ['已确认的旧版本仍保留。修改目的后请再次确认。', 'Versi lama tetap tersimpan. Konfirmasikan lagi setelah mengubah tujuan.', '確認済みの旧バージョンは残ります。目的の変更後、もう一度確認してください。', 'Earlier confirmed versions stay intact. Confirm again after changing your goal.'],
  prefs: ['本次练习偏好', 'Preferensi latihan ini', '今回の練習設定', 'Preferences for this practice'],
  ability: ['这些是练习偏好，听力尚不能判断，口语尚未观察。', 'Ini preferensi latihan. Kemampuan mendengar belum dapat dinilai; berbicara belum diamati.', 'これは練習の希望です。聞く力はまだ判断できず、話す力は未観察です。', 'These are practice preferences. Listening is still unknown; speaking has not been observed.'],
  noMedia: ['真实语音和视频尚未接入', 'Suara dan video sebenarnya belum terhubung', '実際の音声と動画はまだ接続していません', 'Real audio and video are not connected'],
  dialogue: ['准备对话', 'Siapkan percakapan', '会話を準備', 'Prepare dialogue'],
  media: ['准备声音和画面', 'Siapkan suara dan gambar', '音声と映像を準備', 'Prepare audio and visuals'],
  check: ['检查草稿', 'Periksa draf', '下書きを確認', 'Check draft'],
  pending: ['等待演示操作', 'Menunggu tindakan demo', 'デモ操作待ち', 'Waiting for a demo action'],
  done: ['模拟就绪', 'Siap dalam simulasi', 'シミュレーションで準備完了', 'Ready in simulation'],
  failed: ['模拟失败', 'Gagal dalam simulasi', 'シミュレーションで失敗', 'Simulated failure'],
  mediaFailed: ['声音和画面未就绪（模拟）', 'Suara dan gambar belum siap (simulasi)', '音声と映像が未完了です（シミュレーション）', 'Audio and visuals are not ready (simulation)'],
  retry: ['只重试失败部分', 'Ulangi hanya bagian yang gagal', '失敗した部分だけ再試行', 'Retry only the failed part'],
  cancel: ['取消准备', 'Batalkan persiapan', '準備をキャンセル', 'Cancel preparation'],
  controls: ['演示准备控制', 'Kontrol demo persiapan', '準備デモの操作', 'Preparation demo controls'],
  controlHint: ['依次点按以查看就绪或失败状态。这里不会播放、录音或调用生成服务。', 'Ketuk berurutan untuk melihat status siap atau gagal. Tidak memutar, merekam, atau memanggil layanan pembuatan.', '順に押して完了や失敗の状態を確認します。再生、録音、生成サービスの呼び出しは行いません。', 'Tap in order to preview readiness or failure. This does not play, record, or call a generation service.'],
  dialogueReady: ['模拟对话就绪', 'Simulasikan percakapan siap', '会話の準備完了を模擬', 'Simulate dialogue ready'],
  dialogueFailed: ['模拟对话失败', 'Simulasikan percakapan gagal', '会話の失敗を模擬', 'Simulate dialogue failure'],
  mediaReady: ['模拟声音和画面就绪', 'Simulasikan suara dan gambar siap', '音声と映像の準備完了を模擬', 'Simulate audio and visuals ready'],
  mediaFailureControl: ['模拟声音和画面失败', 'Simulasikan suara dan gambar gagal', '音声と映像の失敗を模擬', 'Simulate audio and visuals failure'],
  checkReady: ['模拟检查通过', 'Simulasikan pemeriksaan lulus', '確認の通過を模擬', 'Simulate check passed'],
  checkFailed: ['模拟检查失败', 'Simulasikan pemeriksaan gagal', '確認の失敗を模擬', 'Simulate check failed'],
  steps: ['示例步骤', 'Contoh langkah', '手順の例', 'Example steps'],
  prompts: ['练习提示', 'Petunjuk latihan', '練習のヒント', 'Practice prompts'],
  back: ['返回学习起点', 'Kembali ke titik awal belajar', '学習の出発点に戻る', 'Back to learning starting point'],
  newGoal: ['选择另一件事', 'Pilih hal lain', '別の用件を選ぶ', 'Choose another goal'],
  readError: ['场景读取失败，旧场景记录保持不变；本次可临时预览。', 'Situasi tidak dapat dibaca. Catatan lama tetap utuh; pratinjau sementara masih tersedia.', '場面を読み込めませんでした。以前の記録はそのまま残し、今回は一時的にプレビューできます。', 'The scenario could not be read. The old record stays unchanged; you can preview temporarily.'],
  saveError: ['场景暂时无法保存，本次仍可继续', 'Situasi belum dapat disimpan. Anda masih dapat melanjutkan saat ini.', '場面を保存できませんが、今回はそのまま続けられます', 'The scenario could not be saved. You can still continue for now.'],
} satisfies Record<string, Translation>;
export function scenarioCopy(language: EntryLanguage) {
  return Object.fromEntries(Object.entries(labels).map(([key, values]) => [key, values[index[language]]])) as Record<keyof typeof labels, string>;
}
