import type { EntryLanguage } from './entry-copy';
type Translation = readonly [string, string, string, string];
const index: Record<EntryLanguage, number> = { 'zh-Hans': 0, id: 1, ja: 2, ko: 3, hi: 3 };
const labels = {
  entry: ['选择要练的事', 'Pilih hal yang ingin dilatih', '練習したいことを選ぶ', 'Choose what to practise'],
  title: ['你想练什么事？', 'Apa yang ingin Anda latih?', 'どんなことを練習したいですか？', 'What would you like to practise?'],
  intro: ['从一件近期想办的事开始。可以选一个起点，也可以用熟悉的语言说自己的目的。', 'Mulai dari satu hal yang ingin Anda lakukan. Pilih titik awal atau ceritakan tujuan dalam bahasa yang nyaman.', '近いうちにしたいことから始めましょう。例を選んでも、使い慣れた言葉で目的を伝えても構いません。', 'Start with something you want to do soon. Choose an example or describe your goal in a familiar language.'],
  demo: ['离线整理演示，不是实际生成', 'Demo penyusunan offline, bukan pembuatan sebenarnya', 'オフラインで整理するデモです。実際の生成ではありません', 'Offline planning demo, not actual generation'],
  demoHint: ['这里用通用沟通模板演示步骤，不表示已理解任意需求。辅助语言文案尚未经母语审查。', 'Langkah memakai templat komunikasi umum, bukan pemahaman semua kebutuhan. Teks belum ditinjau penutur asli.', '一般的な会話テンプレートで流れを示します。あらゆる要望を理解したわけではありません。文面は母語話者による未確認です。', 'These steps use generic communication templates, without claiming to understand every request. Translations have not had native-speaker review.'],
  starts: ['场景起点', 'Titik awal situasi', '場面の出発点', 'Scenario starting points'],
  school: ['家校沟通', 'Komunikasi dengan sekolah', '学校とのやりとり', 'School conversations'],
  work: ['工作沟通', 'Komunikasi kerja', '仕事でのやりとり', 'Work conversations'],
  daily: ['生活服务', 'Layanan sehari-hari', '暮らしのサービス', 'Everyday services'],
  custom: ['都不是，我想练……', 'Bukan ini, saya ingin berlatih…', 'どれでもない、練習したいことは…', 'None of these, I want to practise…'],
  description: ['想练的事', 'Hal yang ingin dilatih', '練習したいこと', 'What you want to practise'],
  describeHint: ['例如：陪邻居向物业询问维修时间。只说你愿意留下的内容。', 'Contoh: menemani tetangga menanyakan waktu perbaikan. Tulis hanya yang ingin Anda simpan.', '例：近所の人と修理の時間を窓口で聞きたい。残したい内容だけを書いてください。', 'For example: help a neighbour ask about repair times. Only include what you want to keep.'],
  privacy: ['无需真实姓名、学校、雇主或病历', 'Tidak perlu nama asli, sekolah, pemberi kerja, atau rekam medis', '実名、学校名、勤務先、診療記録は不要です', 'No real names, schools, employers, or medical records are needed'],
  voice: ['用语音描述（尚未接入）', 'Ceritakan dengan suara (belum terhubung)', '声で説明する（未接続）', 'Describe by voice (not connected)'],
  submit: ['整理成确认卡', 'Susun kartu konfirmasi', '確認カードにまとめる', 'Make a confirmation card'],
  clarifyTitle: ['你希望办成什么？', 'Apa yang ingin Anda capai?', '何をできるようになりたいですか？', 'What do you want to accomplish?'],
  clarifyHint: ['先补这一个目的，其他不知道的内容可以留空。', 'Cukup tambahkan tujuan ini. Hal lain yang belum diketahui boleh kosong.', 'まず目的だけを教えてください。ほかの不明なことは空欄で構いません。', 'Add just this goal. Other unknown details can stay blank.'],
  continue: ['继续确认', 'Lanjutkan konfirmasi', '確認へ進む', 'Continue to confirmation'],
  card: ['确认场景', 'Konfirmasi situasi', '場面を確認', 'Confirm the situation'],
  who: ['和谁', 'Dengan siapa', '誰と', 'Who with'], where: ['在哪里', 'Di mana', 'どこで', 'Where'],
  goal: ['希望办成什么', 'Hal yang ingin dicapai', '実現したいこと', 'What you want to accomplish'],
  worry: ['最担心哪一步', 'Bagian yang dikhawatirkan', '一番心配なところ', 'What worries you most'],
  unknown: ['待确认', 'Belum dikonfirmasi', '未確認', 'To be confirmed'],
  userProvided: ['用户提供', 'Diberikan pengguna', '利用者からの情報', 'User-provided'],
  seed: ['来自规格中的练习种子，人物与情境为演示', 'Contoh dari spesifikasi; tokoh dan situasi untuk demo', '仕様書の練習例です。人物と場面はデモ用です', 'Practice seed from the specification; people and setting are illustrative'],
  editWho: ['修改谁', 'Ubah lawan bicara', '相手を変える', 'Change who'],
  editWhere: ['修改地点', 'Ubah tempat', '場所を変える', 'Change place'],
  editGoal: ['修改目的', 'Ubah tujuan', '目的を変える', 'Change goal'],
  editWorry: ['修改担心', 'Ubah kekhawatiran', '心配なことを変える', 'Change concern'],
  save: ['保存修改', 'Simpan perubahan', '変更を保存', 'Save changes'],
  discard: ['返回确认', 'Kembali ke konfirmasi', '確認に戻る', 'Back to confirmation'],
  candidates: ['可选的练习方向', 'Pilihan fokus latihan', '選べる練習の方向', 'Practice focus options'],
  candidateHint: ['保留你的目的，一次只练一个沟通重点。', 'Tujuan Anda tetap sama; latih satu fokus komunikasi sekaligus.', '目的はそのままに、一度に一つのやりとりを練習します。', 'Keep your goal and practise one communication focus at a time.'],
  confirm: ['确认并预览准备', 'Konfirmasi dan pratinjau persiapan', '確認して準備をプレビュー', 'Confirm and preview preparation'],
  preparing: ['正在准备（流程演示）', 'Sedang menyiapkan (demo alur)', '準備中（流れのデモ）', 'Preparing (flow demo)'],
  partial: ['部分准备未就绪（演示）', 'Sebagian persiapan belum siap (demo)', '準備の一部が未完了です（デモ）', 'Some preparation is not ready (demo)'],
  ready: ['场景草稿已备好（演示）', 'Draf situasi sudah siap (demo)', '場面の下書きができました（デモ）', 'Scenario draft is ready (demo)'],
  cancelled: ['已取消准备', 'Persiapan dibatalkan', '準備をキャンセルしました', 'Preparation cancelled'],
  version: ['版本 {n}', 'Versi {n}', 'バージョン {n}', 'Version {n}'],
  view: ['查看版本 {n}', 'Lihat versi {n}', 'バージョン {n} を見る', 'View version {n}'],
  history: ['已确认的版本', 'Versi yang dikonfirmasi', '確認済みのバージョン', 'Confirmed versions'],
  unchanged: ['已确认的旧版本仍保留。修改目的后请再次确认。', 'Versi lama tetap tersimpan. Konfirmasikan lagi setelah mengubah tujuan.', '確認済みの旧バージョンは残ります。目的の変更後、もう一度確認してください。', 'Earlier confirmed versions stay intact. Confirm again after changing your goal.'],
  prefs: ['本次练习偏好', 'Preferensi latihan ini', '今回の練習設定', 'Preferences for this practice'],
  ability: ['这些是练习偏好，听力尚不能判断，口语尚未观察。', 'Ini preferensi latihan. Kemampuan mendengar belum dapat dinilai; berbicara belum diamati.', 'これは練習の希望です。聞く力はまだ判断できず、話す力は未観察です。', 'These are practice preferences. Listening is still unknown; speaking has not been observed.'],
  noMedia: ['真实语音和视频尚未接入', 'Suara dan video sebenarnya belum terhubung', '実際の音声と動画はまだ接続していません', 'Real audio and video are not connected'],
  dialogue: ['准备对话', 'Siapkan percakapan', '会話を準備', 'Prepare dialogue'],
  media: ['准备声音和画面', 'Siapkan suara dan gambar', '音声と映像を準備', 'Prepare audio and visuals'],
  check: ['检查草稿', 'Periksa draf', '下書きを確認', 'Check draft'],
  pending: ['等待演示操作', 'Menunggu tindakan demo', 'デモ操作待ち', 'Waiting for a demo action'],
  done: ['模拟就绪', 'Siap dalam simulasi', 'シミュレーションで準備完了', 'Ready in simulation'],
  failed: ['模拟失败', 'Gagal dalam simulasi', 'シミュレーションで失敗', 'Simulated failure'],
  mediaFailed: ['声音和画面未就绪（模拟）', 'Suara dan gambar belum siap (simulasi)', '音声と映像が未完了です（シミュレーション）', 'Audio and visuals are not ready (simulation)'],
  retry: ['只重试失败部分', 'Ulangi hanya bagian yang gagal', '失敗した部分だけ再試行', 'Retry only the failed part'],
  cancel: ['取消准备', 'Batalkan persiapan', '準備をキャンセル', 'Cancel preparation'],
  controls: ['演示准备控制', 'Kontrol demo persiapan', '準備デモの操作', 'Preparation demo controls'],
  controlHint: ['依次点按以查看就绪或失败状态。这里不会播放、录音或调用生成服务。', 'Ketuk berurutan untuk melihat status siap atau gagal. Tidak memutar, merekam, atau memanggil layanan pembuatan.', '順に押して完了や失敗の状態を確認します。再生、録音、生成サービスの呼び出しは行いません。', 'Tap in order to preview readiness or failure. This does not play, record, or call a generation service.'],
  dialogueReady: ['模拟对话就绪', 'Simulasikan percakapan siap', '会話の準備完了を模擬', 'Simulate dialogue ready'],
  dialogueFailed: ['模拟对话失败', 'Simulasikan percakapan gagal', '会話の失敗を模擬', 'Simulate dialogue failure'],
  mediaReady: ['模拟声音和画面就绪', 'Simulasikan suara dan gambar siap', '音声と映像の準備完了を模擬', 'Simulate audio and visuals ready'],
  mediaFailureControl: ['模拟声音和画面失败', 'Simulasikan suara dan gambar gagal', '音声と映像の失敗を模擬', 'Simulate audio and visuals failure'],
  checkReady: ['模拟检查通过', 'Simulasikan pemeriksaan lulus', '確認の通過を模擬', 'Simulate check passed'],
  checkFailed: ['模拟检查失败', 'Simulasikan pemeriksaan gagal', '確認の失敗を模擬', 'Simulate check failed'],
  steps: ['示例步骤', 'Contoh langkah', '手順の例', 'Example steps'],
  prompts: ['练习提示', 'Petunjuk latihan', '練習のヒント', 'Practice prompts'],
  back: ['返回学习起点', 'Kembali ke titik awal belajar', '学習の出発点に戻る', 'Back to learning starting point'],
  newGoal: ['选择另一件事', 'Pilih hal lain', '別の用件を選ぶ', 'Choose another goal'],
  readError: ['场景读取失败，旧场景记录保持不变；本次可临时预览。', 'Situasi tidak dapat dibaca. Catatan lama tetap utuh; pratinjau sementara masih tersedia.', '場面を読み込めませんでした。以前の記録はそのまま残し、今回は一時的にプレビューできます。', 'The scenario could not be read. The old record stays unchanged; you can preview temporarily.'],
  saveError: ['场景暂时无法保存，本次仍可继续', 'Situasi belum dapat disimpan. Anda masih dapat melanjutkan saat ini.', '場面を保存できませんが、今回はそのまま続けられます', 'The scenario could not be saved. You can still continue for now.'],
} satisfies Record<string, Translation>;
const extra: Record<'ko'|'hi',Partial<Record<keyof typeof labels,string>>>={
  ko:{entry:'연습할 일 선택',title:'무엇을 연습하고 싶나요?',intro:'가까운 시일에 할 일 하나부터 시작하세요.',demo:'오프라인 정리 데모이며 실제 생성이 아닙니다',demoHint:'일반 대화 템플릿으로 흐름을 보여 줍니다. 번역은 아직 원어민 검토 전입니다.',starts:'상황 시작점',school:'학교와 선생님과의 대화',work:'직장 대화',daily:'일상 서비스',custom:'해당 없음, 다른 일을 연습할래요…',description:'연습할 일',describeHint:'예: 이웃과 관리실에 수리 시간을 묻기. 저장할 내용만 입력하세요.',privacy:'실명, 학교, 직장 또는 의료 기록은 필요하지 않습니다',voice:'음성으로 설명(아직 연결되지 않음)',submit:'확인 카드 만들기',clarifyTitle:'무엇을 이루고 싶나요?',clarifyHint:'목적 하나만 추가하세요. 모르는 내용은 비워 둘 수 있습니다.',continue:'확인 계속',card:'상황 확인',who:'누구와',where:'어디에서',goal:'이루고 싶은 일',worry:'가장 걱정되는 부분',unknown:'확인 필요',userProvided:'사용자 제공',seed:'사양의 연습 예시이며 인물과 상황은 데모입니다',editWho:'상대 변경',editWhere:'장소 변경',editGoal:'목적 변경',editWorry:'걱정 변경',save:'변경 저장',discard:'확인으로 돌아가기',candidates:'연습 방향 선택',candidateHint:'목적은 유지하고 한 번에 한 가지 대화에 집중하세요.',confirm:'확인하고 준비 미리보기',preparing:'준비 중(흐름 데모)',partial:'일부 준비가 되지 않음(데모)',ready:'상황 초안 준비 완료(데모)',cancelled:'준비 취소됨',version:'버전 {n}',view:'버전 {n} 보기',history:'확인된 버전',unchanged:'이전 버전은 그대로 보관됩니다. 목적을 바꾸면 다시 확인하세요.',prefs:'이번 연습 선호도',ability:'연습 선호도입니다. 듣기는 아직 판단할 수 없고 말하기는 관찰되지 않았습니다.',noMedia:'실제 음성과 영상은 아직 연결되지 않았습니다',dialogue:'대화 준비',media:'음성과 화면 준비',check:'초안 확인',pending:'데모 조작 대기',done:'시뮬레이션 준비 완료',failed:'시뮬레이션 실패',mediaFailed:'음성과 화면이 준비되지 않음(시뮬레이션)',retry:'실패한 부분만 다시 시도',cancel:'준비 취소',controls:'준비 제어',controlHint:'순서대로 눌러 준비 또는 실패 상태를 확인합니다.',dialogueReady:'대화 준비 완료 시뮬레이션',dialogueFailed:'대화 실패 시뮬레이션',mediaReady:'음성과 화면 준비 완료 시뮬레이션',mediaFailureControl:'음성과 화면 실패 시뮬레이션',checkReady:'검사 통과 시뮬레이션',checkFailed:'검사 실패 시뮬레이션',steps:'예시 단계',prompts:'연습 힌트',back:'학습 시작점으로',newGoal:'다른 일 선택',readError:'상황을 읽을 수 없습니다. 이전 기록은 유지됩니다.',saveError:'상황을 저장할 수 없지만 계속할 수 있습니다.'},
  hi:{entry:'अभ्यास के लिए स्थिति चुनें',title:'आप क्या अभ्यास करना चाहते हैं?',intro:'जल्द किए जाने वाले एक काम से शुरू करें।',demo:'ऑफ़लाइन योजना डेमो, असली निर्माण नहीं',demoHint:'यह सामान्य बातचीत के नमूनों से प्रक्रिया दिखाता है। अनुवाद की मातृभाषी समीक्षा अभी नहीं हुई।',starts:'स्थिति की शुरुआत',school:'स्कूल और शिक्षक से बातचीत',work:'काम की बातचीत',daily:'रोज़मर्रा की सेवाएँ',custom:'इनमें नहीं, मैं यह अभ्यास करना चाहता/चाहती हूँ…',description:'अभ्यास की स्थिति',describeHint:'उदाहरण: पड़ोसी के साथ मरम्मत का समय पूछना। केवल वही लिखें जिसे सहेजना चाहते हैं।',privacy:'असली नाम, स्कूल, नियोक्ता या मेडिकल रिकॉर्ड की ज़रूरत नहीं',voice:'आवाज़ से बताएँ (अभी जुड़ा नहीं)',submit:'पुष्टि कार्ड बनाएँ',clarifyTitle:'आप क्या हासिल करना चाहते हैं?',clarifyHint:'सिर्फ यह लक्ष्य जोड़ें। बाकी अनजान बातें खाली रह सकती हैं।',continue:'पुष्टि जारी रखें',card:'स्थिति की पुष्टि',who:'किसके साथ',where:'कहाँ',goal:'क्या हासिल करना है',worry:'सबसे अधिक चिंता',unknown:'पुष्टि बाकी',userProvided:'उपयोगकर्ता ने दिया',seed:'स्पेसिफ़िकेशन का अभ्यास नमूना; पात्र और स्थिति केवल डेमो हैं',editWho:'व्यक्ति बदलें',editWhere:'जगह बदलें',editGoal:'लक्ष्य बदलें',editWorry:'चिंता बदलें',save:'बदलाव सहेजें',discard:'पुष्टि पर लौटें',candidates:'अभ्यास के विकल्प',candidateHint:'लक्ष्य बनाए रखें और एक बार में एक बातचीत का अभ्यास करें।',confirm:'पुष्टि करें और तैयारी देखें',preparing:'तैयारी हो रही है (फ़्लो डेमो)',partial:'कुछ तैयारी पूरी नहीं (डेमो)',ready:'स्थिति का मसौदा तैयार (डेमो)',cancelled:'तैयारी रद्द',version:'संस्करण {n}',view:'संस्करण {n} देखें',history:'पुष्टि किए संस्करण',unchanged:'पुराने संस्करण सुरक्षित रहते हैं। लक्ष्य बदलने के बाद फिर पुष्टि करें।',prefs:'इस अभ्यास की पसंद',ability:'ये अभ्यास की पसंद हैं। सुनना अभी अज्ञात है और बोलना देखा नहीं गया।',noMedia:'असली आवाज़ और वीडियो अभी जुड़े नहीं हैं',dialogue:'बातचीत तैयार करें',media:'आवाज़ और चित्र तैयार करें',check:'मसौदा जाँचें',pending:'डेमो कार्रवाई की प्रतीक्षा',done:'डेमो में तैयार',failed:'डेमो विफल',mediaFailed:'आवाज़ और चित्र तैयार नहीं (डेमो)',retry:'केवल विफल हिस्सा फिर करें',cancel:'तैयारी रद्द करें',controls:'तैयारी नियंत्रण',controlHint:'तैयार या विफल स्थिति देखने के लिए क्रम से दबाएँ।',dialogueReady:'बातचीत तैयार होने का डेमो',dialogueFailed:'बातचीत विफल होने का डेमो',mediaReady:'आवाज़ और चित्र तैयार होने का डेमो',mediaFailureControl:'आवाज़ और चित्र विफल होने का डेमो',checkReady:'जाँच पास होने का डेमो',checkFailed:'जाँच विफल होने का डेमो',steps:'उदाहरण के कदम',prompts:'अभ्यास संकेत',back:'सीखने की शुरुआत पर लौटें',newGoal:'दूसरी स्थिति चुनें',readError:'स्थिति पढ़ी नहीं जा सकी। पुराना रिकॉर्ड सुरक्षित है।',saveError:'स्थिति सहेजी नहीं जा सकी; अभी जारी रख सकते हैं।'}
};
export function scenarioCopy(language: EntryLanguage) {
  const base=Object.fromEntries(Object.entries(labels).map(([key, values]) => [key, values[index[language]]]));
  return {...base,...(language==='ko'||language==='hi'?extra[language]:{})} as Record<keyof typeof labels, string>;
}
